### ISSUE TITLE
Displaying errors in views over socket mode is unclear or broken

### ISSUE THREAD

**Issue by afilbert** [slack-go/slack#1013]
### What happened

Calling `Ack` with a payload on modal view submission behaves unexpectedly.

### Expected behavior

[Displaying errors in views](https://api.slack.com/surfaces/modals/using#displaying_errors) should highlight the appropriate block/field.

### Steps to reproduce

1. Handle a `view_submission` interaction.
2. Pass the `errors` response action as payload.
3. Observe that modal displays a generic "trouble connecting" error.

<img width="553" alt="Screen Shot 2021-12-28 at 11 00 08 PM" src="https://user-images.githubusercontent.com/523157/147628961-552004b6-81a0-4d5b-85bf-16bafafd26b2.png">

#### code

```
case slack.InteractionTypeViewSubmission:
	result := d.handleFormSubmission(interaction)
	if (FormError{}) != result {
		payload := slack.NewErrorsViewSubmissionResponse(map[string]string{
			result.Key: result.Message,
		})
		d.socketService.Ack(*event.Request, payload)
		return
	}
```

#### manifest.yaml

```
_metadata:
  major_version: 1
  minor_version: 1
display_information:
  name: Mentor Match - dev
features:
  app_home:
    home_tab_enabled: false
    messages_tab_enabled: true
    messages_tab_read_only_enabled: false
  bot_user:
    display_name: Mentor Match
    always_online: true
  slash_commands:
    - command: /mentor-match
      description: Start Mentor Matching
      should_escape: false
    - command: /mentor-stop
      description: Stop Mentor Matching
      should_escape: false
oauth_config:
  scopes:
    bot:
      - app_mentions:read
      - channels:read
      - chat:write
      - chat:write.customize
      - commands
      - conversations.connect:read
      - conversations.connect:write
      - incoming-webhook
      - users.profile:read
      - users:read
      - users:read.email
      - users:write
      - im:write
settings:
  event_subscriptions:
    bot_events:
      - app_mention
  interactivity:
    is_enabled: true
  org_deploy_enabled: false
  socket_mode_enabled: true
  token_rotation_enabled: false
```

### Versions
- Go: 1.17.3
- slack-go/slack: v0.9.5
