### ISSUE TITLE
User email is empty

### ISSUE THREAD

**Issue by loeffel-io** [slack-go/slack#1017]
```go
switch eventsApiEvent.Type {
	case slackevents.CallbackEvent:
		innerEvent := eventsApiEvent.InnerEvent
		switch eventData := innerEvent.Data.(type) {
		case *slackevents.TeamJoinEvent:
                    log.Printf("%+v", eventData.User.Profile.Email) // empty
```

everything else looks fine

#### manifest.yaml

```yaml
_metadata:
  major_version: 1
  minor_version: 1
display_information:
  name: CRM
features:
  bot_user:
    display_name: BotCRM
    always_online: true
oauth_config:
  scopes:
    bot:
      - users:read
      - users:read.email
      - users.profile:read
settings:
  event_subscriptions:
    request_url: xxx
    bot_events:
      - team_join
  org_deploy_enabled: false
  socket_mode_enabled: false
  token_rotation_enabled: false
```

### Versions
- Go: go version go1.17.5 darwin/amd64
- slack-go/slack: 0.10.1
