### ISSUE TITLE
Using slack-go for new slack app

### ISSUE THREAD

**Issue by Qsick** [slack-go/slack#827]
I have been trying to follow the examples but have been unsuccessful to get it to authenticate properly.  It is returning an error related to RTM and that would be the classic bot OAuth from my understanding.  

Does this library support the use of tokens for new slack apps instead of classic?  If so could someone direct me to an example?

**Comment by lenalebt** [comment]
Hey, did you succeed doing so? I'm currently trying to learn go on a useful project, and a small slack bot sounded useful, but this is really a show-stopper currently for me. Would be <3 to get some pointers (alternative projects are also fine)...

**Comment by Qsick** [comment]
It will work for me using the Slack classic tokens but I haven't gotten it
to working using the bot token for the new Slack API.

**Comment by kanata2** [comment]
Could you share reproducible code?

**Comment by lenalebt** [comment]
I fell back to also using the classic tokens, which I think are only available if you add some query parameter to the URL where you need to set the credentials up for your app in slack (I don't remember exactly, but it was along the lines of "token=classic" or "classic=true"). When you have one of those, the code from the repo works well.

**Comment by kunal15145** [comment]
Still can't use the slack-go with the new slack token, It gives  `not_allowed_token_type` error.
Only 2 options remain, use Events API or create a classic slack app token. Any 3rd option?

**Comment by xNok** [comment]
@kunal15145. If you only need a bot and don't what to bother with the slack app configuration. Use https://slack.com/apps/A0F7YS25R-bots, this will add a bot in your workplace and provide you with the token for that bot (xoxb-...). I use that solution when I want to test things out, I hope it helps in your case.

**Comment by renta** [comment]
Faced the same issue today, almost in the end of 2021! A brand new slack app, app and bot token for websocket connection:
```go
slackApi := slack.New(conf.Slack.BotToken, slack.OptionAppLevelToken(conf.Slack.AppToken), slack.OptionDebug(conf.Slack.Debug))
slackRtm := slackApi.NewRTM()
go slackRtm.ManageConnection()
```
and `Failed to start or connect to RTM: not_allowed_token_type` as a result. Seems that modern slack bots can not be connected to Slack via websocket.

**Comment by sheldonhull** [comment]
Not sure if this a related, but thought I'd link in case this is useful. #941

**Comment by xcsrz** [comment]
This is easily reproduceable by attempting the [Minimal Socket Mode usage](https://github.com/slack-go/slack/blob/master/examples/socketmode/socketmode.go) code with the app manifest from [slack's documentation for socket mode](https://api.slack.com/apis/connections/socket#creating):
```
_metadata:
  major_version: 1
display_information:
  name: Demo App
features:
  bot_user:
    display_name: Demo App
    always_online: false
oauth_config:
  scopes:
    bot:
      - app_mentions:read
settings:
  event_subscriptions:
    bot_events:
      - app_mention
  org_deploy_enabled: false
  socket_mode_enabled: true
  is_hosted: false
  token_rotation_enabled: false
```

I came to this just by looking to run a socket mode test and found no manifest file example in this repo.

The discrepancy here is the new/current Slack only requires/suggests a bot level token to make use of sockets, while `slack-go` requires an app level token and (even thought a positional parameter) appears to have the bot level token as optional.

As slack proceeds to transition to the more granular and their oauth2v2 grant model this is likely to become more of an issue.

For me personally this might have just killed my ability to write my latest bot task in go at all :-(
